# Generated by Django 6.1.2 on 2026-10-07 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='cname',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='appointment',
            old_name='cphone',
            new_name='customer_phone',
        ),
    ]
